apiVersion: skaffold/v1beta2
kind: Config
build:
  artifacts:
    - image: bar-au-db
      context: src/bar-au-db
    - image: pgweb
      context: dev-tools/pgweb
    - image: db-migrate-up
      context: src/bar-au-db
      docker: 
        dockerfile: db-migrate-up.Dockerfile
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
      - kubernetes-manifests/bar-au-db.yaml
      - kubernetes-manifests/pgweb.yaml
      - configs/bar-au-db-config.yaml
profiles:
  # "travis-ci" profile is used to build the images withou
  # pushing them.
  - name: travis-ci
    build:
      local:
        push: false
