# Base image
FROM postgres:11.1-alpine

# Expose ports
EXPOSE 5432

# Healthcheck
ADD ./docker-healthcheck.sh /usr/local/bin/docker-healthcheck
RUN chmod +x /usr/local/bin/docker-healthcheck
HEALTHCHECK CMD docker-healthcheck

# Grant privileges
# RUN	chown -R postgres:postgres ${PGDATA}

RUN	chown -R postgres:postgres /var/lib/postgresql/data
#  && \
#     chown -R postgres:postgres ${PGHOME} && \
#     chown -R postgres:postgres /pg-secure && \
#     chmod a+rwx /usr/local/lib/postgresql